### ISSUE TITLE
Where to put freshcells_soap_client config ?

### ISSUE THREAD

**Issue by ducho** [freshcells/soap-client-bundle#27]
Hi!
I try to use your bundle, but I missing info where to put this configuration.
Thanks.

```
freshcells_soap_client:
  logger: monolog.logger.soap
  anonymize_logs: # in case you need to anonymize certain elements in the xml logs
    elements:
      - 'GivenName'
      - 'ns1:GivenName'
    attributes: [ 'PhoneNumber' ]
    namespaces:
      dummy: 'http://gcomputer.net/webservices/'
  truncate_element_logs: # in case you need to truncate some elements because values are too long for logging
    elements:
      - 'DailyDilbertResult'
    namespaces:
      dummy: 'http://gcomputer.net/webservices/'
    max_length: 2
  truncate_logs: # in case you need to truncate request/response logs
    max_length: 350
```

The service "Freshcells\SoapClientBundle\Plugin\LogPlugin" has a dependency on a non-existent service "monolog.logger.soap". Did you mean one of these: "monolog.logger", "monolog.logger.console", "monolog.logger.cache", "monolog.logger.mailer", "monolog.logger.php", "monolog.logger.event", "monolog.logger.router", "monolog.logger.debug"?

**Comment by ivoba** [comment]
Hi,
add a `config/packages/soap_client.yaml` file and add your config there.
If you dont have a dedicated logger for soap calls, just add `logger: logger`.

**Comment by ducho** [comment]
Thanks @ivoba! 
I still have one last question. It is still not clear to me how to configure such a request so that it works:
```
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
    <soap12:Body>
        <Login xmlns="http://www.mynamespace.com/">
            <databaseName>mydatabase</databaseName>
            <userName>myusername</userName>
            <password>mypassword</password>
        </Login>
    </soap12:Body>
</soap12:Envelope>```

Can you advice me?

**Comment by ivoba** [comment]
I guess you would have to create the request object/array and pass it to the resource of SoapClient.


```
$myRequest = ['databaseName' => 'aa', ...];  

$response = $this->container->get('Freshcells\SoapClientBundle\SoapClient\SoapClient')->Login($myRequest);
```

**Comment by ducho** [comment]
@ivoba thanks... Now it works.. but I still have empty SOAP requests in the profiler.. is it necessary to activate something in the configuration?
![image](https://user-images.githubusercontent.com/3294883/199507806-aa54ec1d-fec1-4ae9-b92b-1389e9f64a55.png)

**Comment by ivoba** [comment]
@ducho you need to tag the client.

Add this to `config/packages/soap_client.yaml`

```
services:
    _instanceof:
        Freshcells\SoapClientBundle\SoapClient\SoapClient:
            tags: [ 'freshcells_soap_client.client' ]

    Freshcells\SoapClientBundle\SoapClient\SoapClient:
        arguments: ['%soap_wsdl%', '%soap_options%']
        public: true
```

Seems a bit unconvinent, i might improve this later.

**Comment by ducho** [comment]
@ivoba 
I just added _instanceof and it doesn't work. The second DI definition is unusable for me because I use 4 different wsdl configurations for one service.  I use SoapClient like this
```
        $soapClient = new SoapClient(
            'http://endpoint/Authentication.asmx?wsdl', [
                'trace' => 1,
                'soap_version' => SOAP_1_2,
                'uri' => 'http://endpoint/sws/Authentication.asmx',
                'cache_wsdl' => WSDL_CACHE_NONE,
            ]
        );
```
and this is my soap_client.yaml
```
freshcells_soap_client:
  logger: logger

services:
  _instanceof:
    Freshcells\SoapClientBundle\SoapClient\SoapClient:
      tags: [ 'freshcells_soap_client.client' ]
```

**Comment by ivoba** [comment]
@ducho if you create the SoapClient directly in code it will not work.

You need to create it as a service. Then symfony will handle the rest.
Create one client per WSDL and inject the service to where you call them.

```
services:
    _instanceof:
        Freshcells\SoapClientBundle\SoapClient\SoapClient:
            tags: [ 'freshcells_soap_client.client' ]


    app.soap,client_1:
        class: Freshcells\SoapClientBundle\SoapClient\SoapClient
        arguments: ['%soap_wsdl%', '%soap_options%']
```
